(()=>{
'use strict';
const V='V21';
const O={renderAll,renderDashboard,renderChecklist,renderStadium,renderCdc,renderRestes,renderLocals,renderExports,exportGeneralPDF};
let t=null,pending=false;
const editing=()=>{const e=document.activeElement;return !!(e&&(e.matches('input.fc,textarea.fc')||e.isContentEditable))};
function qsave(now=false){const a=current();if(a)a.updatedAt=new Date().toISOString();clearTimeout(t);if(now)save();else t=setTimeout(save,280)}
window.renderAll=function(){if(editing()){pending=true;return}O.renderAll();decorateAll()};
document.addEventListener('focusout',()=>{qsave(true);setTimeout(()=>{if(pending&&!editing()&&!document.querySelector('.mo.open')){pending=false;O.renderAll();decorateAll()}},350)},true);
window.addEventListener('beforeunload',()=>{if(t){clearTimeout(t);try{save()}catch(_){}}});
function hotelItem(a,it){if(!a.items[it])a.items[it]={status:'',temp:'',cooking:'',notify:false,remarks:'',photos:[]};a.items[it].photos=a.items[it].photos||[];return a.items[it]}
function stadiumItem(a,it){if(!a.stadium)migrateAuditData();if(!a.stadium.items[it])a.stadium.items[it]={status:'',temp:'',cooking:'',notify:false,remarks:'',photos:[]};a.stadium.items[it].photos=a.stadium.items[it].photos||[];return a.stadium.items[it]}
window.setItem=function(k,f,v){const a=ensureAudit();if(!a)return;hotelItem(a,unkey(k))[f]=v;qsave(f==='status'||f==='notify');if(f==='status'||f==='notify'){O.renderChecklist();decorateChecklist();O.renderDashboard();decorateDashboard()}};
window.setStadiumItem=function(k,f,v){const a=ensureAudit();if(!a)return;stadiumItem(a,stadiumKey(k))[f]=v;qsave(f==='status'||f==='notify');if(f==='status'||f==='notify'){O.renderStadium();decorateStadium();O.renderDashboard();decorateDashboard()}};
window.setCdcControl=function(k,f,v){const a=ensureAudit();if(!a)return;const c=ensureCdc(a);c.controls[cdcActiveMoment]=c.controls[cdcActiveMoment]||{};c.controls[cdcActiveMoment][k]=c.controls[cdcActiveMoment][k]||{status:'',qty:'',remark:'',photos:[]};c.controls[cdcActiveMoment][k][f]=v;qsave(f==='status');if(f==='status'){O.renderCdc();decorateCdc()}};
window.setLeftoverRef=function(k,f,v){const a=ensureAudit();if(!a)return;const l=ensureLeftoverMoment(a,restesActiveMoment);l.refItems[k]=l.refItems[k]||{qtyValue:'',qtyUnit:'portion',remark:'',photos:[]};l.refItems[k][f]=v;qsave(f==='qtyUnit');if(f==='qtyUnit'){O.renderRestes();decorateRestes()}};
document.addEventListener('input',e=>{const el=e.target;if(!(el instanceof HTMLInputElement||el instanceof HTMLTextAreaElement)||!el.classList.contains('fc'))return;const c=el.getAttribute('onchange')||'';let m=c.match(/^(setItem|setStadiumItem|setCdcControl|setLeftoverRef)\('([^']+)','([^']+)',this\.value\)$/);if(m&&typeof window[m[1]]==='function'){window[m[1]](m[2],m[3],el.value);return}m=c.match(/^updateAudit\('notes',this\.value\)$/);if(m){const a=ensureAudit();if(a){a.notes=el.value;qsave()}return}m=c.match(/^updateStadium\('notes',this\.value\)$/);if(m){const a=ensureAudit();if(a){if(!a.stadium)migrateAuditData();a.stadium.notes=el.value;qsave()}}},true);
async function readImages(files){const out=[];for(const f of Array.from(files||[])){if(!f.type.startsWith('image/'))continue;const raw=await new Promise((r,j)=>{const x=new FileReader();x.onload=()=>r(x.result);x.onerror=j;x.readAsDataURL(f)});out.push(await compressImage(raw,1280,.8))}return out}
function pickMany(cb){const i=document.createElement('input');i.type='file';i.accept='image/*';i.multiple=true;i.hidden=true;document.body.appendChild(i);i.onchange=async()=>{try{const a=await readImages(i.files);if(a.length)cb(a)}catch(e){console.error(e);toast('Import photo impossible')}finally{i.remove()}};i.click()}
window.importForItem=k=>pickMany(imgs=>{const a=ensureAudit();if(!a)return;const v=hotelItem(a,unkey(k));imgs.forEach(src=>v.photos.push({src,at:nowText(),type:'PMS'}));qsave(true);O.renderChecklist();decorateChecklist();toast(`${imgs.length} photo(s) ajoutée(s)`) });
window.importForStadiumItem=k=>pickMany(imgs=>{const a=ensureAudit();if(!a)return;const v=stadiumItem(a,stadiumKey(k));imgs.forEach(src=>v.photos.push({src,at:nowText(),type:'Traiteur'}));qsave(true);O.renderStadium();decorateStadium();toast(`${imgs.length} photo(s) ajoutée(s)`) });
window.importForCdc=k=>pickMany(imgs=>{const a=ensureAudit();if(!a)return;const c=ensureCdc(a);c.controls[cdcActiveMoment]=c.controls[cdcActiveMoment]||{};c.controls[cdcActiveMoment][k]=c.controls[cdcActiveMoment][k]||{status:'',qty:'',remark:'',photos:[]};const v=c.controls[cdcActiveMoment][k];v.photos=v.photos||[];imgs.forEach(src=>v.photos.push({src,at:nowText()}));qsave(true);O.renderCdc();decorateCdc();toast(`${imgs.length} photo(s) ajoutée(s)`) });
window.importForLeftoverRef=k=>pickMany(imgs=>{const a=ensureAudit();if(!a)return;const l=ensureLeftoverMoment(a,restesActiveMoment);l.refItems[k]=l.refItems[k]||{qtyValue:'',qtyUnit:'portion',remark:'',photos:[]};const v=l.refItems[k];v.photos=v.photos||[];imgs.forEach(src=>v.photos.push({src,at:nowText()}));qsave(true);O.renderRestes();decorateRestes();toast(`${imgs.length} photo(s) ajoutée(s)`) });
window.importManyLocals=()=>{const a=ensureAudit();if(!a)return;const z=$('l_zone')?.value||'Autre',s=$('l_status')?.value||'Conforme',c=$('l_comment')?.value||'';pickMany(imgs=>{imgs.slice().reverse().forEach(src=>a.locals.unshift({zone:z,status:s,comment:c,photo:src,at:nowText(),groupId:uid()}));qsave(true);O.renderLocals();decorateLocals();O.renderDashboard();decorateDashboard();toast(`${imgs.length} photo(s) ajoutée(s) au même sujet`)})};
window.importManyStadiumLocals=()=>{const a=ensureAudit();if(!a)return;if(!a.stadium)migrateAuditData();const z=$('st_l_zone')?.value||'Stade',s=$('st_l_status')?.value||'Conforme',c=$('st_l_comment')?.value||'';pickMany(imgs=>{imgs.slice().reverse().forEach(src=>a.stadium.locals.unshift({zone:z,status:s,comment:c,photo:src,at:nowText(),groupId:uid()}));qsave(true);O.renderStadium();decorateStadium();toast(`${imgs.length} photo(s) ajoutée(s) au même sujet`)})};
function stats(sections,bucket){let total=0,answered=0,considered=0,ok=0,bad=0;sections.forEach(s=>s.items.forEach(it=>{total++;const st=(bucket?.[it]?.status)||'';if(st)answered++;if(st&&st!=='non concerné'){considered++;if(st==='conforme')ok++;else bad++}}));return{total,answered,considered,ok,bad,score:considered?Math.round(ok/considered*100):0}}
function card(title,x,tone){return `<div class="v21-score ${tone}"><div><b>${title}</b><strong>${x.score}%</strong></div><small>${x.ok}/${x.considered||0} conformes<br>${x.answered}/${x.total} renseignés<br>${x.bad} à traiter</small></div>`}
function decorateDashboard(){const p=$('page-dashboard'),a=current();if(!p||!a||p.querySelector('#v21scores'))return;const h=stats(CHECK_SECTIONS,a.items||{}),s=stats(STADIUM_SECTIONS,a.stadium?.items||{}),d=document.createElement('div');d.id='v21scores';d.className='card';d.innerHTML=`<div class="card-head"><div class="label">Scores hygiène séparés</div><span class="badge b-ok">${V}</span></div><div class="v21-grid">${card('Audit Hôtel',h,'hotel')}${card('Audit Traiteur',s,'stadium')}</div><div class="hint">Les points N/C ne sont pas comptés dans la note. Les deux audits sont calculés séparément.</div>`;p.querySelector('.ph')?.insertAdjacentElement('afterend',d)}
function labels(root,fn){root?.querySelectorAll('button').forEach(b=>{if((b.getAttribute('onclick')||'').includes(fn+'('))b.textContent='📁 Importer plusieurs photos'})}
function decorateChecklist(){labels($('page-checklist'),'importForItem')}
function decorateCdc(){labels($('page-cdc'),'importForCdc')}
function decorateRestes(){labels($('page-restes'),'importForLeftoverRef')}
function replaceLocalButton(page,needle,handler){const b=Array.from(page?.querySelectorAll('button')||[]).find(x=>(x.getAttribute('onclick')||'').includes(needle));if(b){b.removeAttribute('onclick');b.textContent='📁 Plusieurs photos';b.onclick=handler}}
function decorateLocals(){replaceLocalButton($('page-locals'),"pickFile(d=>saveLocalPhoto(d))",window.importManyLocals)}
function decorateStadium(){const p=$('page-stadium');labels(p,'importForStadiumItem');replaceLocalButton(p,"pickFile(d=>saveStadiumLocalPhoto(d))",window.importManyStadiumLocals)}
function decorateExports(){const p=$('page-exports'),a=current();if(!p||!a)return;const hb=Array.from(p.querySelectorAll('button')).find(b=>(b.getAttribute('onclick')||'')==='exportGeneralPDF()'),sb=Array.from(p.querySelectorAll('button')).find(b=>(b.getAttribute('onclick')||'')==='exportStadiumPDF()');if(hb)hb.textContent='🏨 Rapport Audit Hôtel uniquement';if(sb)sb.textContent='🏟️ Rapport Audit Traiteur uniquement';const w=p.querySelector('.warn');if(w)w.textContent='Les rapports Hôtel et Traiteur sont désormais dissociés, avec des notes de conformité indépendantes.';if(!p.querySelector('#v21exportscores')){const h=stats(CHECK_SECTIONS,a.items||{}),s=stats(STADIUM_SECTIONS,a.stadium?.items||{}),d=document.createElement('div');d.id='v21exportscores';d.className='card';d.innerHTML=`<div class="label" style="margin-bottom:10px">Synthèse avant export</div><div class="v21-grid">${card('Hôtel',h,'hotel')}${card('Traiteur',s,'stadium')}</div>`;w?.insertAdjacentElement('afterend',d)}}
window.renderDashboard=()=>{O.renderDashboard();decorateDashboard()};window.renderChecklist=()=>{O.renderChecklist();decorateChecklist()};window.renderStadium=()=>{O.renderStadium();decorateStadium()};window.renderCdc=()=>{O.renderCdc();decorateCdc()};window.renderRestes=()=>{O.renderRestes();decorateRestes()};window.renderLocals=()=>{O.renderLocals();decorateLocals()};window.renderExports=()=>{O.renderExports();decorateExports()};
window.exportGeneralPDF=function(){const a=ensureAudit();if(!a)return;const st=a.stadium;try{a.stadium=null;O.exportGeneralPDF()}finally{a.stadium=st}};
function style(){if($('v21style'))return;const s=document.createElement('style');s.id='v21style';s.textContent='.v21-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.v21-score{display:flex;justify-content:space-between;gap:15px;padding:16px;border:1px solid var(--border);border-radius:16px;background:var(--bg3)}.v21-score.hotel{box-shadow:inset 4px 0 var(--blue)}.v21-score.stadium{box-shadow:inset 4px 0 var(--gold)}.v21-score b{display:block;font-size:12px;text-transform:uppercase;color:var(--muted)}.v21-score strong{display:block;font:900 30px var(--mono);margin-top:3px}.v21-score small{color:var(--muted);line-height:1.55;text-align:right}@media(max-width:700px){.v21-grid{grid-template-columns:1fr}.v21-score small{text-align:left}}';document.head.appendChild(s)}
function decorateAll(){style();decorateDashboard();decorateChecklist();decorateStadium();decorateCdc();decorateRestes();decorateLocals();decorateExports()}
decorateAll();console.info('[Audit Hôtel Pro] correctifs '+V+' chargés');
})();
